{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "03e35178-6702-4abf-b120-01a34ff5ad5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from dash import Dash, html, dcc, Input, Output, State\n",
    "import dash_bootstrap_components as dbc\n",
    "import pymysql\n",
    "from sqlalchemy import create_engine, text\n",
    "import pandas as pd\n",
    "import plotly.express as px"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "eb37ecfc-6f87-44a3-9672-780a1a2937f7",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "sample_bootstrap = \"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n",
    "app = Dash(external_stylesheets=[sample_bootstrap])  #[dbc.themes.BOOTSTRAP]\n",
    "app.layout = html.Div(\n",
    "    [\n",
    "            dbc.Row(\n",
    "                html.H6(\"1-1\")\n",
    "            ),\n",
    "            dbc.Row(\n",
    "                [\n",
    "                    dbc.Col(\n",
    "                        html.H6(\"2-1\")\n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        html.H6(\"2-2\")\n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        html.H6(\"2-3\")\n",
    "                    ),\n",
    "                ]\n",
    "            ),\n",
    "            dbc.Row(\n",
    "                [\n",
    "                    dbc.Col(\n",
    "                        html.H6(\"3-1\")\n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        html.H6(\"3-2\")\n",
    "                    ),\n",
    "                ]\n",
    "            )\n",
    "    ]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "68c8cc4b-5450-4708-bc91-7a83af53d4ec",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "#app.run_server(host=\"192.168.56.101\",port=6234)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "1505517a-df13-48fa-b1eb-756fca88a625",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "## 데이터 정리\n",
    "# DB접속\n",
    "user = \"bigdata\"\n",
    "password = \"Bigdata123!!\"\n",
    "host = \"192.168.56.101\"\n",
    "port = \"3306\"\n",
    "db = \"SampleDB\"\n",
    "engine = create_engine(f\"mysql+pymysql://{user}:{password}@{host}:{port}/{db}\")\n",
    "conn = engine.connect()\n",
    "continent = pd.read_sql(\"select distinct continent from world\",conn)\n",
    "continent = continent.loc[:,\"continent\"].values\n",
    "year = pd.read_sql(\"select distinct year from world\",conn)\n",
    "year = year.loc[:,\"year\"].values\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "e0a9a23b-a15c-4907-9e4e-aae4d2dd31a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "sample_bootstrap = \"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\n",
    "app = Dash(external_stylesheets=[sample_bootstrap])  #[dbc.themes.BOOTSTRAP]\n",
    "app.layout = html.Div(\n",
    "    [\n",
    "            dbc.Row(\n",
    "                [\n",
    "                    html.Div(\"World pop & GDP\", \n",
    "                             style={\"font-size\":16,\n",
    "                                    \"color\":\"white\",\n",
    "                                    \"bacground-color\":\"black\",\n",
    "                                    \"text-align\":\"center\"})\n",
    "                ]\n",
    "            ),\n",
    "            dbc.Row(\n",
    "                [\n",
    "                    dbc.Col(\n",
    "                        [\n",
    "                        html.Label(\"대륙\",\n",
    "                                    style = {\"font-size\":10}),\n",
    "                        dcc.Dropdown(id=\"dropdown1\",  \n",
    "                                    options = [{\"label\":i, \"value\":i} for i in continent],\n",
    "                                    placeholder = continent[1],\n",
    "                                    style = {\"font-size\":10, \"height\":\"5px\"}\n",
    "                                    ),\n",
    "                               \n",
    "                          ]\n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        [\n",
    "                         html.Label(\"국가\",\n",
    "                                       style = {\"font-size\":10}),\n",
    "                         html.Div(id=\"dropdown-result\",style={\"height\":\"5px\"}),   \n",
    "                        ]\n",
    "                         \n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        [\n",
    "                         html.Label(\"년도\",\n",
    "                                       style={\"font-sise\":10}),\n",
    "                         dcc.Dropdown(id=\"dropdown3\",\n",
    "                                        options = [{\"label\":i, \"value\":i} for i in year],\n",
    "                                        placeholder = year[0],\n",
    "                                        style = {\"font-size\":10, \"height\":\"5px\"})   \n",
    "                        ]\n",
    "                    ),\n",
    "                ]\n",
    "            ),\n",
    "            html.P(),\n",
    "            html.Hr(),\n",
    "            dbc.Row(\n",
    "                [\n",
    "                    dbc.Col(\n",
    "                        dcc.Graph(id=\"bar-graph\")\n",
    "                    ),\n",
    "                    dbc.Col(\n",
    "                        dcc.Graph(id=\"pie-graph\")\n",
    "         \n",
    "                    ),\n",
    "                ]\n",
    "            )\n",
    "    ]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "35db0abf-1d33-4982-8d87-eabf23b0929b",
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output(\"dropdown-result\",\"children\"),\n",
    "    Input(\"dropdown1\",\"value\")\n",
    ")\n",
    "\n",
    "def update_country(continent):\n",
    "    country = pd.read_sql(f\"select distinct country from world where continent = '{continent}'\",conn)\n",
    "    country = country.loc[:,\"country\"].values\n",
    "    return html.Div([\n",
    "        dcc.Dropdown(\n",
    "            id = \"dropdown2\",\n",
    "            options = [{\"label\":i, \"value\":i} for i in country],\n",
    "            style={\"font-size\":10, \"height\":\"5px\"}\n",
    "        )\n",
    "    ])\n",
    "\n",
    "@app.callback(\n",
    "    Output(\"bar-graph\",\"figure\"),\n",
    "    Input(\"dropdown1\",\"value\"),\n",
    "    Input(\"dropdown2\",\"value\"),\n",
    "    Input(\"dropdown3\",\"value\")\n",
    ")\n",
    "def update_bargraph(continent, country, year):\n",
    "    df = pd.read_sql(\"select * from world\",conn)\n",
    "    dt = df.loc[(df.continent==continent) & (df.country==country),[\"year\",\"gdpPercap\"]]\n",
    "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
    "    return fig\n",
    "\n",
    "@app.callback(\n",
    "    Output(\"pie-graph\",\"figure\"),\n",
    "    Input(\"dropdown1\",\"value\"),\n",
    "    Input(\"dropdown2\",\"value\"),\n",
    "    Input(\"dropdown3\",\"value\")\n",
    ")\n",
    "def update_piegraph(continent, country, year):\n",
    "    df = pd.read_sql(\"select * from world\",conn)\n",
    "    dt = df.loc[(df.continent==continent) & (df.country==country) ,[\"year\",\"pop\"]]\n",
    "    fig = px.pie(names=dt.year.values,values=dt.loc[:,\"pop\"].values)\n",
    "    return fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ad596818-82d1-4c39-a8a7-e4e1cb5477e1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>year</th>\n",
       "      <th>gdpPercap</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1952</td>\n",
       "      <td>779.445</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1957</td>\n",
       "      <td>820.853</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1962</td>\n",
       "      <td>853.101</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1967</td>\n",
       "      <td>836.197</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1972</td>\n",
       "      <td>739.981</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>1977</td>\n",
       "      <td>786.113</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>1982</td>\n",
       "      <td>978.011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>1987</td>\n",
       "      <td>852.396</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>1992</td>\n",
       "      <td>649.341</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>1997</td>\n",
       "      <td>635.341</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2002</td>\n",
       "      <td>726.734</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2007</td>\n",
       "      <td>974.580</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    year  gdpPercap\n",
       "0   1952    779.445\n",
       "1   1957    820.853\n",
       "2   1962    853.101\n",
       "3   1967    836.197\n",
       "4   1972    739.981\n",
       "5   1977    786.113\n",
       "6   1982    978.011\n",
       "7   1987    852.396\n",
       "8   1992    649.341\n",
       "9   1997    635.341\n",
       "10  2002    726.734\n",
       "11  2007    974.580"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "    df = pd.read_sql(\"select*from world\",conn)\n",
    "    continent = df.continent[0]\n",
    "    country = df.country[0]\n",
    "    year = df.year[0]\n",
    "    dt = df.loc[(df.continent==continent) & (df.country==country) ,[\"year\",\"gdpPercap\"]]\n",
    "    dt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1bc6295e-ca99-415c-a9e1-550fbc2d8f7c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash_bootstrap_components as dbc\n",
    "from dash import html\n",
    "\n",
    "card = dbc.Card(\n",
    "    [\n",
    "        dbc.CardImg(src=\"/static/images/placeholder286x180.png\", top=True),\n",
    "        dbc.CardBody(\n",
    "            [\n",
    "                html.H4(\"Card title\", className=\"card-title\"),\n",
    "                html.P(\n",
    "                    \"Some quick example text to build on the card title and \"\n",
    "                    \"make up the bulk of the card's content.\",\n",
    "                    className=\"card-text\",\n",
    "                ),\n",
    "                dbc.Button(\"Go somewhere\", color=\"primary\"),\n",
    "            ]\n",
    "        ),\n",
    "    ],\n",
    "    style={\"width\": \"18rem\"},\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8bed9d36-1562-44b9-af9c-998fc83e2617",
   "metadata": {},
   "outputs": [],
   "source": [
    "app = Dash(__name__)\n",
    "app.layout = html.Div(\n",
    "    card\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1590cd50-e986-4e5e-aa6e-4b5ec8027de7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://192.168.56.101:6234/\n",
      "\n",
      "Dash is running on http://192.168.56.101:6234/\n",
      "\n",
      "Dash is running on http://192.168.56.101:6234/\n",
      "\n",
      "Dash is running on http://192.168.56.101:6234/\n",
      "\n",
      "Dash is running on http://192.168.56.101:6234/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.56.101:6234/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:26] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.56.1 - - [14/Feb/2022 23:33:26] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:26] \"POST /_dash-update-component HTTP/1.1\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_12593/1481171348.py\", line 26, in update_bargraph\n",
      "    fig = px.bar(x=dt.year.values,y=dt.gdpPercap.values)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_chart_types.py\", line 368, in bar\n",
      "    return make_figure(\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1945, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"/home/jhyu/anaconda3/lib/python3.9/site-packages/plotly/express/_core.py\", line 1324, in build_dataframe\n",
      "    raise ValueError(\n",
      "ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.56.1 - - [14/Feb/2022 23:33:26] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:26] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:27] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:27] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:33:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:34:50] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:34:50] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:34:51] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [14/Feb/2022 23:34:52] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "app.run_server(host=\"192.168.56.101\",port=6234)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39bc3414-9fab-4dca-b4d7-cbed3a62fd4d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
